# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        Shared\CommandHandling\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.command }

        Shared\CommandHandling\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.query }

        Shared\EventHandling\EventListenerInterface:
            tags:
                - { name: packages.shared.event_handling.event_listener }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/App/*'
        exclude: '../src/App/**/{Migrations,EventSubscriber}'
    UI\:
        resource: '../src/UI/*'
        exclude: '../src/UI/**/{Migrations,EventSubscriber}'

    UI\Cli\Command\:
        resource: '../src/UI/Cli/Command'

    UI\Http\JsonApi\Controller\:
        resource: '../src/UI/Http/JsonApi/Controller/*'
        tags:
            - { name: controller.service_arguments }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

when@test:
    services:
        _defaults: {}

        SharedBundle\CommandHandling\MessengerCommandBus:
            arguments:
                - '@messenger.bus.command'

        Shared\CommandHandling\CommandBusInterface:
            alias: SharedBundle\CommandHandling\MessengerCommandBus
            public: true

        SharedBundle\CommandHandling\MessengerQueryBus:
            arguments:
                - '@messenger.bus.query'

        Shared\CommandHandling\QueryBusInterface:
            alias: SharedBundle\CommandHandling\MessengerQueryBus
            public: true

        Tests\App\EventCollectorListener:
            public: true
            tags:
                - { name: packages.shared.event_handling.event_listener }